[package]
name = "sprite-blitting-rs"
version = "0.1.0"
authors = ["Ysgard <ysgard@gmail.com>"]
edition = "2018"

[dependencies.sdl2]
version = "0.32"
default-features = false
features = ["ttf", "image"]
